image : microsoft/dotnet:latest
stages:
  - build
  - test
before_script:
  - 'dotnet restore'
build:
  stage: build
  script:
    - 'dotnet build'
  only:
    - master
test:
  stage: test
  script:
    - 'dotnet build'
  only:
    - master